---
- hosts: all
  vars:
    repo_dir: /root/pst/
    repo_path: https://github.com/k13132/pst-sdn.git
    password: $6$7yr/SnSVRZZ4e1OZ$v3goGGlFdZ.2dwtXaHJPTHFSkmEacrW2jc/XiB..2dHnCMZC0QgVPK2ONLtRnG96gyzpO.5NllBwSKS/mo6Rh.
  become: yes
  remote_user: ubuntu
  handlers:
    - name: reload ssh
      service: name=ssh state=reloaded
  tasks:
    - name: install packages
      apt: name="{{item}}" state=present update_cache=yes
      with_items:
        - openvswitch-common
        - openvswitch-switch
        - sudo
        - git
        - mininet
        - python-pip
        - build-essential
        - tcpdump
        - iptraf
        - vim
        - python-dev
        - tmux
        - apt-transport-https
        - ca-certificates
        - nmap

    - name: install from pip
      pip: name="{{item}}" state=present
      with_items:
        - virtualenv
        - virtualenvwrapper

    - name: create directory for pst
      file:
        path: "{{repo_dir}}"
        state: directory

    - name: clone repository
      git:
        repo: "{{repo_path}}"
        dest: "{{repo_dir}}"
        update: yes
        force: yes
        version: regulator

    - name: clean files in repository
      file:
        path: "{{repo_dir}}/{{item}}"
        state: absent
      with_items:
        - switch_13.py

    - name: install ryu
      pip:
        chdir: "{{ repo_dir }}"
        requirements: requirements.txt
        virtualenv: "~/.virtualenvs/pst"

    - name: add virtualenv to bashrc
      lineinfile:
        dest: ~/.bashrc
        line: "source ~/.virtualenvs/pst/bin/activate"
        state: present

    - name: allow SSH password login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*'
        line: PasswordAuthentication yes
        state: present
      notify: reload ssh

    - name: set password for ubuntu user
      user:
        name: ubuntu
        password: "{{ password }}"
