---
- hosts: all
  vars:
    repo_dir: /root/pst/
    repo_path: https://github.com/k13132/pst-sdn.git
  become: yes
  remote_user: ubuntu
  handlers:
    - name: reload ssh
      service: name=ssh state=reloaded
  tasks:
    - name: install packages
      apt: name="{{item}}" state=present update_cache=yes
      with_items:
        - openvswitch-common
        - openvswitch-switch
        - sudo
        - git
        - mininet
        - python-pip
        - python-setuptools 
        - python-eventlet 
        - python-lxml 
        - python-msgpack 
        - build-essential
        - tcpdump
        - iptraf
        - vim
        - python-dev
        - tmux
        - apt-transport-https
        - ca-certificates


    - name: install ryu
      pip: name="{{item}}" state=latest
      with_items:
        - ryu
        - oslo.config
        - six
        - repoze.lru
        - debtcollector
        - stevedore

    - name: stop & disable ovs-controller
      service: name=openvswitch-controller state=stopped enabled=no

    - name: create directory for pst
      file:
        path: "{{repo_dir}}"
        state: directory

    - name: clone repository
      git:
        repo: "{{repo_path}}"
        dest: "{{repo_dir}}"
        update: yes

    - name: allow SSH password login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*'
        line: PasswordAuthentication yes
        state: present
      notify: reload ssh
    - name: set password for ubuntu user
      user:
        name: ubuntu
        password: $6$7yr/SnSVRZZ4e1OZ$v3goGGlFdZ.2dwtXaHJPTHFSkmEacrW2jc/XiB..2dHnCMZC0QgVPK2ONLtRnG96gyzpO.5NllBwSKS/mo6Rh.

    # docker
    - name: add docker apt key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

    - name: add docker apt repository
      apt_repository:
        repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main"
        state: present
        update_cache: yes

    - name: install docker-engine
      apt: name=docker-engine state=present install_recommends=no
