---
- hosts: all
  vars:
    repo_dir: /root/pst/
    repo_path: https://github.com/tomkukral/pst_sdn.git
  tasks:
    - name: install packages
      apt: name="{{item}}" state=present
      with_items:
        - openvswitch-common
        - openvswitch-switch
        - sudo
        - git
        - mininet
        - python-pip
        - python-setuptools 
        - python-eventlet 
        - python-lxml 
        - python-msgpack 
        - build-essential

    - name: install ryu
      pip: name="{{item}}" state=present
      with_items:
        - ryu
        - oslo.config

    - name: stop & disable ovs-controller
      service: name=openvswitch-controller state=stopped enabled=no

    - name: create directory for pst
      file:
        path: "{{repo_dir}}"
        state: directory

    - name: clone repository
      git:
        repo: "{{repo_path}}"
        dest: "{{repo_dir}}"
        update: yes

